extends:
  - eslint:recommended
  - plugin:react/recommended

plugins:
  - react

env:
  browser: true
  node: true
  mocha: true
  es6: true

rules:
  no-case-declarations: 0
  no-unused-vars: 1
  quotes: 0
  semi: [2, "always"]

parserOptions:
  sourceType: "module"
  ecmaFeatures:
    jsx: true