# Configuration
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
env:
  browser: true
  node: true
  mocha: true
  es6: true
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - import
settings:
  import/resolver: webpack
  react:
    version: detect

# Rules
rules:
  # Active rules
  no-multiple-empty-lines:
    - warn
    - max: 1
  no-unused-vars: 1
  semi:
    - error
    - always
  spaced-comment:
    - warn
    - always
    - exceptions:
      - '*'

  # Overridden and disabled rules
  no-case-declarations: 0
  no-useless-escape: 0
  import/order:
    - warn
    - 
      groups:
        - external
        - builtin
        - internal
        - sibling
      pathGroups:
        - pattern: "@components/**"
          group: internal
          position: after
        - pattern: "@constants/**"
          group: internal
          position: after
        - pattern: "@reducers/**"
          group: external
          position: after
        - pattern: "@styles/**"
          group: internal
          position: after
      pathGroupsExcludedImportTypes:
        - internal
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true


  import/no-unresolved:
    - 2
    - ignore:
      - "^@"
  react/prop-types: 0
  react/display-name: 0
  quotes: 0
