# Configuration
extends:
  - eslint:recommended
  - plugin:react/recommended
env:
  browser: true
  node: true
  mocha: true
  es6: true
parser: babel-eslint
parserOptions:
  sourceType: 'module'
  ecmaFeatures:
    jsx: true
plugins:
  - react
settings:
  react:
    version: 'detect'

# Rules
rules:
  # Active rules
  no-multiple-empty-lines: [1, max: 1]
  no-unused-vars: 1
  semi: [2, 'always']
  spaced-comment: [1, 'always', exceptions: ['*']]

  # Overriden and disabled rules
  no-case-declarations: 0
  no-useless-escape: 0
  react/prop-types: 0
  quotes: 0
